version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      # install dependencies in both apps
      - run:
          name: frontend install packages
          command: |
            npm --prefix ./reactnd-contacts-complete run install
      - run:
          name: backend install packages
          command: |
            npm --prefix ./reactnd-contacts-server run install
      - run:
          name: backend build
          command: |
            npm --prefix ./reactnd-contacts-server run build
      - run:
          name: frontend build
          command: |
            npm --prefix ./reactnd-contacts-complete run build
