version: 2.1
orbs:
  # orgs contain basc recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.1.0
  # different jobs are calles later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      # install dependencies in both apps
      - run:
          name: Front-end install
          command: |
            cd reactnd-contacts-complete && npm install
      - run:
          name: Back-end install
          command: | 
            cd reactnd-contacts-server && npm install
      - run:
          name: Front-end build
          command: |
            cd reactnd-contacts-complete && npm run build
      - run:
          name: Back-end build
          command: |
            cd reactnd-contacts-server && npm run build
      